<?php

namespace AppBundle\Repository;

/**
 * RefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPublic()
    {
        return $this->createQueryBuilder('ref')
            ->andWhere('ref.status= :status')
            ->setParameter('status', 'public')
            ->getQuery()
            ->execute();
    }
}
