<?php

namespace AppBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPublic()
    {
        return $this->createQueryBuilder('tag')
            ->andWhere('tag.status= :status')
            ->setParameter('status', 'public')
            ->getQuery()
            ->execute();
    }

    public function findAllPending()
    {
        return $this->createQueryBuilder('tag')
            ->andWhere('tag.status= :status')
            ->setParameter('status', 'pending')
            ->getQuery()
            ->execute();
    }
}
