# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    app.doctrine.password_listener:
        class: AppBundle\Doctrine\PasswordListener
        autowire: true
        tags:
            - {name: doctrine.event_subscriber}
